export const errorInput: string;
export const errorText: string;
export const fullPage: string;
export const highlightText: string;
export const mainButton: string;
export const mainInput: string;
export const mainPage: string;
export const whiteButton: string;
export const whiteInput: string;
